name: Playwright CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 2 * * *'

jobs:
#   test:
#     runs-on: [self-hosted, Windows, X64]

#     steps:

#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Playwright Browsers
#         run: npx playwright install

#       - name: Run Playwright Tests
#         id: tests
#         run: npx playwright test --reporter=html
#         continue-on-error: true

#       - name: Upload Playwright Report
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: playwright-report/

#       # Slack Success
#       - name: Slack Notification Success
#         if: success()
#         shell: powershell
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           $msg = @{
#             text = "✅ Playwright Tests Passed `nRepo: $env:GITHUB_REPOSITORY `nBranch: $env:GITHUB_REF_NAME `nRun: https://github.com/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID"
#           } | ConvertTo-Json -Compress

#           Invoke-RestMethod -Uri $env:SLACK_WEBHOOK_URL -Method Post -Body $msg -ContentType "application/json"

#       # Slack Failure
#       - name: Slack Notification Failure
#         if: failure()
#         shell: powershell
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           $msg = @{
#             text = "❌ Playwright Tests Failed `nRepo: $env:GITHUB_REPOSITORY `nBranch: $env:GITHUB_REF_NAME `nRun: https://github.com/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID"
#           } | ConvertTo-Json -Compress

#           Invoke-RestMethod -Uri $env:SLACK_WEBHOOK_URL -Method Post -Body $msg -ContentType "application/json"

 slack-test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Send Slack Test Message
        shell: powershell
        run: |
          $webhook = "PASTE_YOUR_SLACK_WEBHOOK_URL_HERE"

          $payload = @{
          text = "🚀 Slack test message from GitHub Actions"
          } | ConvertTo-Json -Compress

          Invoke-RestMethod -Uri $webhook -Method Post -Body $payload -ContentType "application/json"

      - name: Debug Slack URL
        shell: powershell
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if (-not $env:SLACK_WEBHOOK_URL) {
                  Write-Host "Slack URL is EMPTY"
          } else {
                Write-Host "Slack URL exists"
          }      